In [345]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [346]:
import random
import numpy as np
import pandas as pd
import scipy.special
import matplotlib.pyplot as plt

In [347]:
class neuralNetwork:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # make nodes. input nodes, hidden nodes, output nodes
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # make weights. by normal distribution
        self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        
        # self.output_delta = np.zeros(outputnodes) + 1e-7
        # self.hidden_delta = np.zeros(outputnodes) + 1e-7
        
        # set learning rate
        self.lr = learningrate
        
        self.sigmoid = lambda x: 1 / (1 + np.exp(-x))
        # self.grad_sigmoid = lambda x: self.sigmoid(x) * (1.0 - self.sigmoid(x))
        
        # self.getError = lambda y, t: y - t
        # self.mse = lambda y, t: (1/2) * np.sum((y - t) ** 2)
        # self.mse = lambda y, t: np.mean(np.square(t - y))
        # self.cross_entropy = lambda y, t, d: -np.sum(t * np.log(y + d)) / y.shape[0]
        # self.mse_rm = lambda y, t: 2/2 * (y - t)
        # self.deriv_mse = lambda w, x, t: np.dot((np.dot(w, x) - t), x.T)
        # self.mse_deriv = lambda t, a2, z, a1: - (t - a2) * self.sigmoid(z) * (1.0 - self.sigmoid(z)) * a1
        # self.mse_deriv2 = lambda a1, z, a0: a1 * self.sigmoid(z) * (1.0 - self.sigmoid(z)) * a0
        
        self.mse_doda = lambda t, a: (t - a)
        self.mse_dadz = lambda z: self.sigmoid(z) * self.sigmoid(z)
        self.mse_dzdw = lambda a: a
        
        
        pass
    
    def train(self, inputs_list, targets_list):
        inputs = np.array(inputs_list, ndmin = 2).T
        targets = np.array(targets_list, ndmin = 2).T
        
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.sigmoid(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.sigmoid(final_inputs)
       
    
        # get error
        
        output_errors = - np.dot(np.dot(self.mse_doda(targets_list, final_outputs.T), self.mse_dadz(final_inputs)), self.mse_dzdw(hidden_outputs).T)
        hidden_errors = np.dot(np.dot(output_errors, self.mse_dadz(hidden_inputs)), self.mse_dzdw(inputs).T)
        
        
        # output_errors = self.mse_deriv(targets_list, final_outputs, final_inputs, hidden_outputs)
        # hidden_errors = self.mse_deriv2(output_errors, hidden_inputs, inputs)
        
        
        """
        output_errors = self.deriv_mse(self.who, hidden_outputs, targets_list)
        hidden_errors = np.dot(self.who.T, output_errors)
        """
        
        
        """
        self.output_delta = self.mse_rm(final_outputs, targets_list)
        output_errors = np.dot(self.output_delta, np.transpose(hidden_outputs))
        delta = 0.0
        delta = delta + np.dot(np.transpose(self.output_delta), self.who)
        self.hidden_delta = self.mse_rm(delta, self.who)
        hidden_errors = np.dot(self.hidden_delta, inputs)
        """
        
        # self.output_delta = np.dot(np.subtract(final_outputs, targets_list), np.transpose(self.grad_sigmoid(final_inputs)))
        # output_errors = np.dot(self.output_delta, hidden_outputs)
        # hidden_delta = 0.0
        # hidden_delta = hidden_delta + np.dot(self.output_delta, self.who)
        # self.hidden_delta = np.dot(hidden_delta, self.grad_sigmoid(hidden_inputs))
        # hidden_errors = np.dot(self.hidden_delta, np.transpose(inputs))
        
        
        # update weight
        self.who = self.who - output_errors * self.lr
        self.wih = self.wih - hidden_errors * self.lr
        
        
        pass
        
    def query(self, inputs_list):
        inputs = np.array(inputs_list, ndmin = 2).T
        
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.sigmoid(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.sigmoid(final_inputs)
        
        return final_outputs

In [348]:
input_nodes = 2
hidden_nodes = 2
output_nodes = 2

learning_rate = 0.01

n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [349]:
training_data_list = [[3.5064385449265267, 2.34547092892632525, 0],
                   [4.384621956392097, 3.4530853889904205, 0],
                   [4.841442919897487, 4.02507852317520154, 0],
                   [3.5985868973088437, 4.1621314217538705, 0],
                   [2.887219775424049, 3.31523082529190005, 0],
                   [9.79822645535526, 1.1052409596099566, 1],
                   [7.8261241795117422, 0.6711054766067182, 1],
                   [2.5026163932400305, 5.800780055043912, 1],
                   [5.032436157202415, 8.650625621472184, 1],
                   [4.095084253434162, 7.69104329159447, 1]]

In [350]:
test_data_list = [[3.5064385449265267, 2.34547092892632525, 0],
                   [4.384621956392097, 3.4530853889904205, 0],
                   [4.841442919897487, 4.02507852317520154, 0],
                   [3.5985868973088437, 4.1621314217538705, 0],
                   [2.887219775424049, 3.31523082529190005, 0],
                   [9.79822645535526, 1.1052409596099566, 1],
                   [7.8261241795117422, 0.6711054766067182, 1],
                   [2.5026163932400305, 5.800780055043912, 1],
                   [5.032436157202415, 8.650625621472184, 1],
                   [4.095084253434162, 7.69104329159447, 1]]

In [351]:
epochs = 10

for i in range(epochs):
    for record in training_data_list:
        all_values = record
    
        inputs = (np.asfarray(all_values[0:2]))
        
        targets = (np.asfarray(all_values[2]))
    
        n.train(inputs, targets)
        pass
    if (i % 2 == 0):
        print("--------------------------------------")
        print("epochs:", i)
        all_values
        inputs
        print(targets)
        
        scorecard = []

        for record_ in test_data_list:
            all_values_ = record_
            correct_label_ = int(all_values_[2])
            inputs_ = (np.asfarray(all_values_[0:2]))
            outputs_ = n.query(inputs_)
            label_ = np.argmax(outputs_)
            
            outputs_
            
            print(correct_label_, "      correct label")
            print(label_, "       prediction\n")
            
            
            if label_ == correct_label_:
                scorecard.append(1)
            else:
                scorecard.append(0)
                pass
            pass

        scorecard_array = np.asarray(scorecard)
        print("performance =", scorecard_array.sum() / scorecard_array.size, "\n\n\n")
pass

--------------------------------------
epochs: 0


[4.095084253434162, 7.69104329159447, 1]

array([4.09508425, 7.69104329])

1.0


array([[0.45617661],
       [0.6577931 ]])

0       correct label
1        prediction



array([[0.45323134],
       [0.6617189 ]])

0       correct label
1        prediction



array([[0.45256321],
       [0.66256011]])

0       correct label
1        prediction



array([[0.45401451],
       [0.66079654]])

0       correct label
1        prediction



array([[0.45701214],
       [0.65698296]])

0       correct label
1        prediction



array([[0.45167473],
       [0.66363224]])

1       correct label
1        prediction



array([[0.45189809],
       [0.66330639]])

1       correct label
1        prediction



array([[0.45505634],
       [0.65960663]])

1       correct label
1        prediction



array([[0.4518264 ],
       [0.66346243]])

1       correct label
1        prediction



array([[0.45218534],
       [0.66303808]])

1       correct label
1        prediction

performance = 0.5 



--------------------------------------
epochs: 2


[4.095084253434162, 7.69104329159447, 1]

array([4.09508425, 7.69104329])

1.0


array([[0.45332504],
       [0.65511102]])

0       correct label
1        prediction



array([[0.45034429],
       [0.65906967]])

0       correct label
1        prediction



array([[0.44966894],
       [0.65992077]])

0       correct label
1        prediction



array([[0.45111273],
       [0.65815792]])

0       correct label
1        prediction



array([[0.45411624],
       [0.65433135]])

0       correct label
1        prediction



array([[0.44877375],
       [0.66100631]])

1       correct label
1        prediction



array([[0.44900657],
       [0.66067423]])

1       correct label
1        prediction



array([[0.45209697],
       [0.65702535]])

1       correct label
1        prediction



array([[0.44891964],
       [0.6608411 ]])

1       correct label
1        prediction



array([[0.44927246],
       [0.66042134]])

1       correct label
1        prediction

performance = 0.5 



--------------------------------------
epochs: 4


[4.095084253434162, 7.69104329159447, 1]

array([4.09508425, 7.69104329])

1.0


array([[0.45061263],
       [0.65247779]])

0       correct label
1        prediction



array([[0.44758141],
       [0.6564859 ]])

0       correct label
1        prediction



array([[0.44689348],
       [0.65735301]])

0       correct label
1        prediction



array([[0.4483426 ],
       [0.65557621]])

0       correct label
1        prediction



array([[0.45136874],
       [0.65171816]])

0       correct label
1        prediction



array([[0.44598114],
       [0.65846411]])

1       correct label
1        prediction



array([[0.44622571],
       [0.65812295]])

1       correct label
1        prediction



array([[0.44928226],
       [0.65448619]])

1       correct label
1        prediction



array([[0.4461241 ],
       [0.65830025]])

1       correct label
1        prediction



array([[0.44647594],
       [0.65787908]])

1       correct label
1        prediction

performance = 0.5 



--------------------------------------
epochs: 6


[4.095084253434162, 7.69104329159447, 1]

array([4.09508425, 7.69104329])

1.0


array([[0.44803434],
       [0.64988863]])

0       correct label
1        prediction



array([[0.44493791],
       [0.65396367]])

0       correct label
1        prediction



array([[0.44423207],
       [0.65485313]])

0       correct label
1        prediction



array([[0.44569866],
       [0.65304816]])

0       correct label
1        prediction



array([[0.44876337],
       [0.64914022]])

0       correct label
1        prediction



array([[0.44329219],
       [0.65600224]])

1       correct label
1        prediction



array([[0.44355115],
       [0.65564848]])

1       correct label
1        prediction



array([[0.44660475],
       [0.65198809]])

1       correct label
1        prediction



array([[0.44343473],
       [0.6558368 ]])

1       correct label
1        prediction



array([[0.44379043],
       [0.65540851]])

1       correct label
1        prediction

performance = 0.5 



--------------------------------------
epochs: 8


[4.095084253434162, 7.69104329159447, 1]

array([4.09508425, 7.69104329])

1.0


array([[0.44558638],
       [0.64733799]])

0       correct label
1        prediction



array([[0.4424099 ],
       [0.65149859]])

0       correct label
1        prediction



array([[0.44168071],
       [0.65241715]])

0       correct label
1        prediction



array([[0.44317655],
       [0.65056981]])

0       correct label
1        prediction



array([[0.44629528],
       [0.64659332]])

0       correct label
1        prediction



array([[0.44070255],
       [0.65361741]])

1       correct label
1        prediction



array([[0.44097904],
       [0.65324674]])

1       correct label
1        prediction



array([[0.44405854],
       [0.64952879]])

1       correct label
1        prediction



array([[0.44084701],
       [0.65344768]])

1       correct label
1        prediction



array([[0.44121128],
       [0.65300655]])

1       correct label
1        prediction

performance = 0.5 





In [352]:
scorecard = []

for record in test_data_list:
    all_values = record
    correct_label = int(all_values[2])
    inputs = (np.asfarray(all_values[0:2]))
    outputs = n.query(inputs)
    label = np.argmax(outputs)
    
    outputs
            
    print(correct_label, "      correct label")
    print(label, "       prediction\n")
            
    if label == correct_label:
        scorecard.append(1)
    else:
        scorecard.append(0)
        pass
    pass

scorecard_array = np.asarray(scorecard)
print("performance =", scorecard_array.sum() / scorecard_array.size)

array([[0.44441041],
       [0.64607519]])

0       correct label
1        prediction



array([[0.44118825],
       [0.65028599]])

0       correct label
1        prediction



array([[0.44044526],
       [0.65122179]])

0       correct label
1        prediction



array([[0.44196011],
       [0.64934786]])

0       correct label
1        prediction



array([[0.44511159],
       [0.64532994]])

0       correct label
1        prediction



array([[0.43944373],
       [0.6524529 ]])

1       correct label
1        prediction



array([[0.43973034],
       [0.65207187]])

1       correct label
1        prediction



array([[0.44283324],
       [0.64831269]])

1       correct label
1        prediction



array([[0.43959   ],
       [0.65228002]])

1       correct label
1        prediction



array([[0.43996035],
       [0.65183027]])

1       correct label
1        prediction

performance = 0.5
